### PR TITLE
added get_bucket

### PR DESCRIPTION
**Pull request by vickylihorst**
Added `get_bucket()` to api.py to download a file from a Google bucket. 

The vision is to add `engine` to the [default] section of `.fissconfig`. For example, `engine=gce`.

### CODE REVIEW

**Comment by noblem** [comment]
Vicky, this code is perfectly fine as is, but I wanted to use the PR as a teaching moment in brevity & clarity.  What I'm referring to is the high degree of redundancy in the definition of cmd:
```
if not manifestLogFile:
      cmd = "gsutil -m cp {} {}".format(fileInCloud, file)
else:
    cmd = "gsutil -m cp -L {} {} {}".format(manifestLogFile, fileInCloud, file)
```
This can be shrunk a little, 
```
cmd = "gsutil -m cp {} {}".format(fileInCloud, file)
if manifestLogFile:
    cmd += " -L {}".format(manifestLogFile)
```
or even further
```
cmd = "gsutil -m cp {} {}".format(fileInCloud, file)
if manifestLogFile:
    cmd += " -L " + manifestLogFile
```
Obviously this is neither urgent nor important to address in this PR, but I mention it as a stylistic approach you might consider gradually adopting in your coding.  Even the phrasing of the conditional is slightly easier to process, i.e. in general
```
if <something>
```
is slightly easier to process (for both the computer and our minds) than
```
if not <something>
```
Just a thought ...

**Comment by vickylihorst** [comment]
I see your point, but in this particular example, the order of arguments for `gsutil cp` isn't that flexible. In particular, your example would fail as the `gsutil` command would be:
```
gsutil -m cp <bucket_url> <destination_filename> -L <manifest.log>
```

Note the correct order is:
```
gsutil -m cp -L <manifest.log> <bucket_url> <destination_filename>
```
In theory, one could format `-L <manifest.log>` as a unit to solve this problem, but I think with just 2 cases, it's probably overkill as it would make the command harder to process for our minds, especially considering that FISS is a public-facing tool.

I do agree with the phrasing of the conditional, and I've changed it.

**Comment by noblem** [comment]
Thanks.  Re: gsutil ... that's too bad.  In general the order of optional flags ought to be irrelevant.  -1 for google, it seems.

**Comment by dheiman** [comment]
Noting the subprocess #TODO, once you switch to that, the command has to be an array of strings, so Mike's suggestion will be doable.

**Pull request merged**
