### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by francois-a**
Passes tests.

### CODE REVIEW

**Comment by noblem** [comment]
Does the need for this change reflect that the FireCloud development team actually heeded my suggestion given in this [forum post](http://gatkforums.broadinstitute.org/firecloud/discussion/8972/are-config-namespaces-helpful-necessary-within-workspaces)?

**Comment by francois-a** [comment]
No, this just removes a couple of (undeclared) variables that aren't needed in the API call. I agree with your post, though.

**Comment by noblem** [comment]
Ahh, the joy of undeclared variables (in dynamic languages) going undiscovered until runtime.  To minimize that (and similar errors, like syntax problems) I used pylint in FireBrowse (e.g. how [pylint_wrap](https://github.com/broadinstitute/firebrowse/blob/master/pylint_wrap) is used in this [Makefile](https://github.com/broadinstitute/firebrowse/blob/master/server/Makefile).  It's stripped down to only report true problems (ignoring picky style stuff that Pythonista zealots love to complain about), but it seems like we could use it here as part of the test suite.  What do you think?

**Comment by francois-a** [comment]
Yes, makes sense.

**Comment by noblem** [comment]
Ok, thanks, I've added https://github.com/broadinstitute/fiss/issues/17

**Pull request merged**
